---
# handlers file for postgresql

- name: restart_postgresql
  service:
    name: postgresql
    state: restarted
- name: restart_zabbix_agent
  service:
    name: zabbix-agent
    state: restarted
